### ISSUE TITLE
Gem capitalization

### ISSUE THREAD

**Issue by bycoffe** [dwillis/fech-ftp#6]
The project on Rubygems is [Fech-FTP](https://rubygems.org/gems/Fech-FTP), but the README says to install it with

    $ gem install fech-ftp

which doesn't work, because of different capitalization. It seems like changing the gem name (to be consistent with Fech itself) would be preferable, but since changing the README is also an option, I'll defer to the project owner to decide the best way to handle.

**Comment by wismer** [comment]
Ah good catch - I hadn't thought about that when updating the readme.

**Comment by rdmurphy** [comment]
+1 on this — just ran into it again.

**Comment by dwillis** [comment]
The new version of fech-ftp (0.1.0) fixes this, so give it a whirl.
